export const PanelConfig = [
    {
        name:'filedBase',
        text:'表单组件',
        widgets:[
            {
                name:'input',
                text:'输入框',
                widget:{
                    componentType:'input',
                    properties:{
                        input:{
                            type:'string',
                            widget:'input',
                            label:'输入框',
                            value:'',
                            placeholder:'',
                            width:'',
                            labelWidth:'',
                            required:false,
                        }
                    }
                }
            },
            {
                name:'textarea',
                text:'文本域',
                widget:{
                    componentType:'textarea',
                    properties:{
                        textarea:{
                            type:'string',
                            widget:'textarea',
                            label:'文本域',
                            value:'',
                            placeholder:'',
                            width:'',
                            labelWidth:'',
                            required:false,
                            rows:2
                        }
                    }
                }
            },
            {
                name:'inputNumber',
                text:'数字输入框',
                widget:{
                    componentType:'inputNumber',
                    properties:{
                        inputNumber:{
                            type:'number',
                            widget:'inputNumber',
                            label:'数字输入框',
                            value:0,
                            placeholder:'',
                            width:'',
                            labelWidth:'',
                            required:false,
                            min:1,
                            max:100,
                            precision:0,
                            controlsPosition:''
                        }
                    }
                }
            },
            {
                name:'radio',
                text:'单选框组',
                widget:{
                    componentType:'radio',
                    properties:{
                        radio:{
                            type:'string',
                            widget:'radio',
                            label:'单选框组',
                            value:'',
                            width:'',
                            labelWidth:'',
                            required:false,
                            enum:['r1','r2','r3'],
                            enumNames:['radio1','radio2','radio3'],
                        }
                    }
                }
            },
            {
                name:'checkbox',
                text:'复选框组',
                widget:{
                    componentType:'checkbox',
                    properties:{
                        checkbox:{
                            type:'array',
                            widget:'checkbox',
                            label:'复选框组',
                            value:[],
                            width:'',
                            labelWidth:'',
                            required:false,
                            enum:['c1','c2','c3'],
                            enumNames:['checkbox1','checkbox2','checkbox3'],
                        }
                    }
                }
            },
            {
                name:'select',
                text:'下拉选择器',
                widget:{
                    componentType:'select',
                    properties:{
                        select:{
                            type:'string',
                            widget:'select',
                            label:'下拉选择器',
                            value:'',
                            width:'',
                            labelWidth:'',
                            placeholder:'请选择',
                            required:false,
                            enum:['s1','s2','s3'],
                            enumNames:['select1','select2','select3'],
                        }
                    }
                }
            },
            {
                name:'switch',
                text:'开关',
                widget:{
                    componentType:'switch',
                    properties:{
                        switch:{
                            type:'boolean',
                            widget:'switch',
                            label:'开关',
                            value:false,
                            width:'',
                            labelWidth:'',
                            required:false,
                        }
                    }
                }
            },
            {
                name:'slider',
                text:'滑块',
                widget:{
                    componentType:'slider',
                    properties:{
                        slider:{
                            type:'number',
                            widget:'slider',
                            label:'滑块',
                            value:0,
                            width:'',
                            labelWidth:'',
                            required:false,
                            max:100,
                            minx:0
                        }
                    }
                }
            },
            {
                name:'datePicker',
                text:'日期选择器',
                widget:{
                    componentType:'datePicker',
                    properties:{
                        datePicker:{
                            type:'number',
                            widget:'datePicker',
                            label:'日期选择器',
                            width:'',
                            labelWidth:'',
                            required:false,
                            format:'YYYY-MM-DD',
                        }
                    }
                }
            },
            {
                name:'text',
                text:'文字',
                widget:{
                    componentType:'text',
                    properties:{
                        text:{
                            widget:'text',
                            label:'文字',
                            value:'文字标签'
                        }
                    }
                }
            },
            {
                name:'textLink',
                text:'文字链接',
                widget:{
                    componentType:'textLink',
                    properties:{
                        textLink:{
                            widget:'textLink',
                            label:'文字链接',
                            value:'文字链接',
                            underline:true,
                        }
                    }
                }
            },
            {
                name:'html',
                text:'HTML',
                widget:{
                    componentType:'html',
                    properties:{
                        html:{
                            widget:'html',
                            label:'HTML',
                            value:'<b style="color: #409eff;">这是一段HTML代码</b>'
                        }
                    }
                }
            },
            {
                name:'cascader',
                text:'级联选择器',
                widget:{
                    componentType:'cascader',
                    properties:{
                        cascader:{
                            widget:'cascader',
                            label:'级联',
                            value:[],
                            options:[{"value":"Option 1","label":"Option 1","children":[{"value":"Option 1 - children","label":"Option 1 - children"}]},{"value":"Option 2","label":"Option 2","children":[{"value":"Option 2 - children","label":"Option 2 - children"}]},{"value":"Option 3","label":"Option 3"}]
                        }
                    }
                }
            },
            {
                name:'button',
                text:'按钮',
                widget:{
                    componentType:'button',
                    properties:{
                        button:{
                            widget:'button',
                            label:'按钮',
                            labelName:'按钮',
                            size:'default',
                            text:''
                        }
                    }
                }
            }
        ]
    },
    {
        name:'filedAdvance',
        text:'高级组件',
        widgets:[
            {
                name:'upload',
                text:'上传文件',
                widget:{
                    componentType:'upload',
                    properties:{
                        upload:{
                            type:'string',
                            widget:'upload',
                            label:'上传文件',
                            fileList:[],
                            width:'100%',
                            labelWidth:'',
                            required:false,
                            name:'file',
                            action:'http://3888z2k945.wicp.vip:6079/qy/api/upload/management/uploadFile'
                        }
                    }
                }
            },
            {
                name:'uploadImg',
                text:'上传图片',
                widget:{
                    componentType:'uploadImg',
                    properties:{
                        uploadImg:{
                            type:'string',
                            widget:'uploadImg',
                            label:'上传图片',
                            fileList:[],
                            width:'',
                            labelWidth:'',
                            required:false,
                            name:'file',
                            action:'http://3888z2k945.wicp.vip:6079/qy/api/upload/management/uploadFile'
                        }
                    }
                }
            },
            // {
            //     name:'dataTable',
            //     text:'数据表格',
            //     widget:{
            //         componentType:'dataTable',
            //         properties:{
            //             dataTable:{
            //                 type:'string',
            //                 widget:'dataTable',
            //                 label:'数据表格',
            //                 width:'',
            //                 labelWidth:'',
            //                 required:false,
            //             }
            //         }
            //     }
            // }
        ]
    },
    {
        name:'filedLayout',
        text:'布局组件',
        widgets:[
            {
                name:'layoutRow',
                text:'栅格布局',
                widget:{
                    componentType:'layoutRow',
                    properties:{
                        layoutRow:{
                            type:'number',
                            widget:'layoutRow',
                            label:'栅格布局',
                            gutter:0,
                            justify:'start',
                            align:'top'
                        }
                    },
                    children:[
                        {
                            name:'layoutCol',
                            text:'栅格列',
                            widget:{
                                componentType:'layoutCol',
                                properties:{
                                    layoutCol:{
                                        type:'number',
                                        widget:'layoutCol',
                                        label:'栅格列',
                                        span:12,
                                        offset:0,
                                        push:0,
                                        pull:0
                                    }
                                }
                            }
                        }
                    ]
                }
            },
            {
                name:'layoutCard',
                text:'卡片布局',
                widget:{
                    componentType:'layoutCard',
                    properties:{
                        layoutCard:{
                            type:'number',
                            widget:'layoutCard',
                            label:'卡片布局',
                            header:'标题',
                            shadow:'always',
                            padding:'10px',
                        }
                    },
                    children:[

                    ]
                }
            },
            {
                name:'layoutTable',
                text:'表格布局',
                widget:{
                    componentType:'layoutTable',
                    properties:{
                        layoutTable:{
                            type:'number',
                            widget:'layoutTable',
                            label:'表格布局',
                            width:'100%',
                            borderWidth:'1px',
                            borderColor:'rgb(153, 153, 153)',
                            totalRows:2,
                            totalThWidth:['']
                        }
                    },
                    children:[
                        {
                            name:'layoutTableCell',
                            text:'单元格',
                            widget:{
                                componentType:'layoutTableCell',
                                properties:{
                                    layoutTableCell:{
                                        type:'number',
                                        widget:'layoutTableCell',
                                        label:'单元格',
                                        height:'30px',
                                        colspan:1,
                                        rowspan:1,
                                        isMerged:false,
                                        textAlign:'',
                                        verticalAlign:''
                                    }
                                }
                            }
                        }
                    ]
                }
            },
            {
                name:'divider',
                text:'分割线',
                widget:{
                    componentType:'divider',
                    properties:{
                        divider:{
                            type:'number',
                            widget:'divider',
                            label:'分割线',
                            contentPosition:'center',
                            borderStyle:'solid',
                            direction:'horizontal'
                        }
                    },
                    children:[

                    ]
                }
            },
        ]
    }
]
export default PanelConfig